// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Target.proto

#ifndef PROTOBUF_INCLUDED_Target_2eproto
#define PROTOBUF_INCLUDED_Target_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "AISData.pb.h"
#include "CommonEnum.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Target_2eproto 

namespace protobuf_Target_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Target_2eproto
class PBTarget;
class PBTargetDefaultTypeInternal;
extern PBTargetDefaultTypeInternal _PBTarget_default_instance_;
class PBTargetAssociation_DS_Mass;
class PBTargetAssociation_DS_MassDefaultTypeInternal;
extern PBTargetAssociation_DS_MassDefaultTypeInternal _PBTargetAssociation_DS_Mass_default_instance_;
class PBTargetPosition;
class PBTargetPositionDefaultTypeInternal;
extern PBTargetPositionDefaultTypeInternal _PBTargetPosition_default_instance_;
namespace google {
namespace protobuf {
template<> ::PBTarget* Arena::CreateMaybeMessage<::PBTarget>(Arena*);
template<> ::PBTargetAssociation_DS_Mass* Arena::CreateMaybeMessage<::PBTargetAssociation_DS_Mass>(Arena*);
template<> ::PBTargetPosition* Arena::CreateMaybeMessage<::PBTargetPosition>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class PBTarget : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBTarget) */ {
 public:
  PBTarget();
  virtual ~PBTarget();

  PBTarget(const PBTarget& from);

  inline PBTarget& operator=(const PBTarget& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PBTarget(PBTarget&& from) noexcept
    : PBTarget() {
    *this = ::std::move(from);
  }

  inline PBTarget& operator=(PBTarget&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PBTarget& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBTarget* internal_default_instance() {
    return reinterpret_cast<const PBTarget*>(
               &_PBTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PBTarget* other);
  friend void swap(PBTarget& a, PBTarget& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PBTarget* New() const final {
    return CreateMaybeMessage<PBTarget>(NULL);
  }

  PBTarget* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PBTarget>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PBTarget& from);
  void MergeFrom(const PBTarget& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBTarget* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PBTargetPosition listTargetPos = 3;
  int listtargetpos_size() const;
  void clear_listtargetpos();
  static const int kListTargetPosFieldNumber = 3;
  ::PBTargetPosition* mutable_listtargetpos(int index);
  ::google::protobuf::RepeatedPtrField< ::PBTargetPosition >*
      mutable_listtargetpos();
  const ::PBTargetPosition& listtargetpos(int index) const;
  ::PBTargetPosition* add_listtargetpos();
  const ::google::protobuf::RepeatedPtrField< ::PBTargetPosition >&
      listtargetpos() const;

  // uint32 sequenceNum = 1;
  void clear_sequencenum();
  static const int kSequenceNumFieldNumber = 1;
  ::google::protobuf::uint32 sequencenum() const;
  void set_sequencenum(::google::protobuf::uint32 value);

  // .PB_Enum_Software enum_Sender_Software = 2;
  void clear_enum_sender_software();
  static const int kEnumSenderSoftwareFieldNumber = 2;
  ::PB_Enum_Software enum_sender_software() const;
  void set_enum_sender_software(::PB_Enum_Software value);

  // @@protoc_insertion_point(class_scope:PBTarget)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::PBTargetPosition > listtargetpos_;
  ::google::protobuf::uint32 sequencenum_;
  int enum_sender_software_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Target_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBTargetPosition : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBTargetPosition) */ {
 public:
  PBTargetPosition();
  virtual ~PBTargetPosition();

  PBTargetPosition(const PBTargetPosition& from);

  inline PBTargetPosition& operator=(const PBTargetPosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PBTargetPosition(PBTargetPosition&& from) noexcept
    : PBTargetPosition() {
    *this = ::std::move(from);
  }

  inline PBTargetPosition& operator=(PBTargetPosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PBTargetPosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBTargetPosition* internal_default_instance() {
    return reinterpret_cast<const PBTargetPosition*>(
               &_PBTargetPosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PBTargetPosition* other);
  friend void swap(PBTargetPosition& a, PBTargetPosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PBTargetPosition* New() const final {
    return CreateMaybeMessage<PBTargetPosition>(NULL);
  }

  PBTargetPosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PBTargetPosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PBTargetPosition& from);
  void MergeFrom(const PBTargetPosition& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBTargetPosition* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string countryName = 9;
  void clear_countryname();
  static const int kCountryNameFieldNumber = 9;
  const ::std::string& countryname() const;
  void set_countryname(const ::std::string& value);
  #if LANG_CXX11
  void set_countryname(::std::string&& value);
  #endif
  void set_countryname(const char* value);
  void set_countryname(const char* value, size_t size);
  ::std::string* mutable_countryname();
  ::std::string* release_countryname();
  void set_allocated_countryname(::std::string* countryname);

  // .PBAISDynamic aisDynamic = 2;
  bool has_aisdynamic() const;
  void clear_aisdynamic();
  static const int kAisDynamicFieldNumber = 2;
  private:
  const ::PBAISDynamic& _internal_aisdynamic() const;
  public:
  const ::PBAISDynamic& aisdynamic() const;
  ::PBAISDynamic* release_aisdynamic();
  ::PBAISDynamic* mutable_aisdynamic();
  void set_allocated_aisdynamic(::PBAISDynamic* aisdynamic);

  // .PBAISStatic aisStatic = 3;
  bool has_aisstatic() const;
  void clear_aisstatic();
  static const int kAisStaticFieldNumber = 3;
  private:
  const ::PBAISStatic& _internal_aisstatic() const;
  public:
  const ::PBAISStatic& aisstatic() const;
  ::PBAISStatic* release_aisstatic();
  ::PBAISStatic* mutable_aisstatic();
  void set_allocated_aisstatic(::PBAISStatic* aisstatic);

  // .PBAISVoyage aisVoyage = 4;
  bool has_aisvoyage() const;
  void clear_aisvoyage();
  static const int kAisVoyageFieldNumber = 4;
  private:
  const ::PBAISVoyage& _internal_aisvoyage() const;
  public:
  const ::PBAISVoyage& aisvoyage() const;
  ::PBAISVoyage* release_aisvoyage();
  ::PBAISVoyage* mutable_aisvoyage();
  void set_allocated_aisvoyage(::PBAISVoyage* aisvoyage);

  // int32 targetID = 1;
  void clear_targetid();
  static const int kTargetIDFieldNumber = 1;
  ::google::protobuf::int32 targetid() const;
  void set_targetid(::google::protobuf::int32 value);

  // .PB_Enum_TargetInfo_Type enum_targetInfoType = 5;
  void clear_enum_targetinfotype();
  static const int kEnumTargetInfoTypeFieldNumber = 5;
  ::PB_Enum_TargetInfo_Type enum_targetinfotype() const;
  void set_enum_targetinfotype(::PB_Enum_TargetInfo_Type value);

  // .PB_Enum_TargetInfo_Source enum_targetInfoSource = 6;
  void clear_enum_targetinfosource();
  static const int kEnumTargetInfoSourceFieldNumber = 6;
  ::PB_Enum_TargetInfo_Source enum_targetinfosource() const;
  void set_enum_targetinfosource(::PB_Enum_TargetInfo_Source value);

  // .PB_Enum_TargetID_Type enum_TargetIDOrig_Type = 7;
  void clear_enum_targetidorig_type();
  static const int kEnumTargetIDOrigTypeFieldNumber = 7;
  ::PB_Enum_TargetID_Type enum_targetidorig_type() const;
  void set_enum_targetidorig_type(::PB_Enum_TargetID_Type value);

  // int32 targetIDOrig = 8;
  void clear_targetidorig();
  static const int kTargetIDOrigFieldNumber = 8;
  ::google::protobuf::int32 targetidorig() const;
  void set_targetidorig(::google::protobuf::int32 value);

  // .PB_Enum_Aggregated_AIS_Ship_Type aggregatedAISShipType = 10;
  void clear_aggregatedaisshiptype();
  static const int kAggregatedAISShipTypeFieldNumber = 10;
  ::PB_Enum_Aggregated_AIS_Ship_Type aggregatedaisshiptype() const;
  void set_aggregatedaisshiptype(::PB_Enum_Aggregated_AIS_Ship_Type value);

  // int32 cargoType = 11;
  void clear_cargotype();
  static const int kCargoTypeFieldNumber = 11;
  ::google::protobuf::int32 cargotype() const;
  void set_cargotype(::google::protobuf::int32 value);

  // uint32 lastAssocUsingDSCombinationUTCTime = 14;
  void clear_lastassocusingdscombinationutctime();
  static const int kLastAssocUsingDSCombinationUTCTimeFieldNumber = 14;
  ::google::protobuf::uint32 lastassocusingdscombinationutctime() const;
  void set_lastassocusingdscombinationutctime(::google::protobuf::uint32 value);

  // int32 beidouID = 15;
  void clear_beidouid();
  static const int kBeidouIDFieldNumber = 15;
  ::google::protobuf::int32 beidouid() const;
  void set_beidouid(::google::protobuf::int32 value);

  // int32 haijianID = 16;
  void clear_haijianid();
  static const int kHaijianIDFieldNumber = 16;
  ::google::protobuf::int32 haijianid() const;
  void set_haijianid(::google::protobuf::int32 value);

  // int32 argosAndMarineSatID = 17;
  void clear_argosandmarinesatid();
  static const int kArgosAndMarineSatIDFieldNumber = 17;
  ::google::protobuf::int32 argosandmarinesatid() const;
  void set_argosandmarinesatid(::google::protobuf::int32 value);

  // bool isDangerShip = 13;
  void clear_isdangership();
  static const int kIsDangerShipFieldNumber = 13;
  bool isdangership() const;
  void set_isdangership(bool value);

  // bool isInterestTarget = 32;
  void clear_isinteresttarget();
  static const int kIsInterestTargetFieldNumber = 32;
  bool isinteresttarget() const;
  void set_isinteresttarget(bool value);

  // bool isWarShip = 34;
  void clear_iswarship();
  static const int kIsWarShipFieldNumber = 34;
  bool iswarship() const;
  void set_iswarship(bool value);

  // bool isLawEnforceShip = 35;
  void clear_islawenforceship();
  static const int kIsLawEnforceShipFieldNumber = 35;
  bool islawenforceship() const;
  void set_islawenforceship(bool value);

  // .PB_Enum_Target_ThreatLevel enum_TargetThreadLevel = 31;
  void clear_enum_targetthreadlevel();
  static const int kEnumTargetThreadLevelFieldNumber = 31;
  ::PB_Enum_Target_ThreatLevel enum_targetthreadlevel() const;
  void set_enum_targetthreadlevel(::PB_Enum_Target_ThreatLevel value);

  // .PB_Enum_Target_XGSCustomizedThreatLevel enum_XGSCustomizedTargetThreadLevel = 33;
  void clear_enum_xgscustomizedtargetthreadlevel();
  static const int kEnumXGSCustomizedTargetThreadLevelFieldNumber = 33;
  ::PB_Enum_Target_XGSCustomizedThreatLevel enum_xgscustomizedtargetthreadlevel() const;
  void set_enum_xgscustomizedtargetthreadlevel(::PB_Enum_Target_XGSCustomizedThreatLevel value);

  // bool isChinese = 36;
  void clear_ischinese();
  static const int kIsChineseFieldNumber = 36;
  bool ischinese() const;
  void set_ischinese(bool value);

  // uint32 zoneEntryTimes = 37;
  void clear_zoneentrytimes();
  static const int kZoneEntryTimesFieldNumber = 37;
  ::google::protobuf::uint32 zoneentrytimes() const;
  void set_zoneentrytimes(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PBTargetPosition)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr countryname_;
  ::PBAISDynamic* aisdynamic_;
  ::PBAISStatic* aisstatic_;
  ::PBAISVoyage* aisvoyage_;
  ::google::protobuf::int32 targetid_;
  int enum_targetinfotype_;
  int enum_targetinfosource_;
  int enum_targetidorig_type_;
  ::google::protobuf::int32 targetidorig_;
  int aggregatedaisshiptype_;
  ::google::protobuf::int32 cargotype_;
  ::google::protobuf::uint32 lastassocusingdscombinationutctime_;
  ::google::protobuf::int32 beidouid_;
  ::google::protobuf::int32 haijianid_;
  ::google::protobuf::int32 argosandmarinesatid_;
  bool isdangership_;
  bool isinteresttarget_;
  bool iswarship_;
  bool islawenforceship_;
  int enum_targetthreadlevel_;
  int enum_xgscustomizedtargetthreadlevel_;
  bool ischinese_;
  ::google::protobuf::uint32 zoneentrytimes_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Target_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PBTargetAssociation_DS_Mass : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBTargetAssociation_DS_Mass) */ {
 public:
  PBTargetAssociation_DS_Mass();
  virtual ~PBTargetAssociation_DS_Mass();

  PBTargetAssociation_DS_Mass(const PBTargetAssociation_DS_Mass& from);

  inline PBTargetAssociation_DS_Mass& operator=(const PBTargetAssociation_DS_Mass& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PBTargetAssociation_DS_Mass(PBTargetAssociation_DS_Mass&& from) noexcept
    : PBTargetAssociation_DS_Mass() {
    *this = ::std::move(from);
  }

  inline PBTargetAssociation_DS_Mass& operator=(PBTargetAssociation_DS_Mass&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PBTargetAssociation_DS_Mass& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PBTargetAssociation_DS_Mass* internal_default_instance() {
    return reinterpret_cast<const PBTargetAssociation_DS_Mass*>(
               &_PBTargetAssociation_DS_Mass_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(PBTargetAssociation_DS_Mass* other);
  friend void swap(PBTargetAssociation_DS_Mass& a, PBTargetAssociation_DS_Mass& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PBTargetAssociation_DS_Mass* New() const final {
    return CreateMaybeMessage<PBTargetAssociation_DS_Mass>(NULL);
  }

  PBTargetAssociation_DS_Mass* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PBTargetAssociation_DS_Mass>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PBTargetAssociation_DS_Mass& from);
  void MergeFrom(const PBTargetAssociation_DS_Mass& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBTargetAssociation_DS_Mass* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double associationMass = 2;
  void clear_associationmass();
  static const int kAssociationMassFieldNumber = 2;
  double associationmass() const;
  void set_associationmass(double value);

  // int32 targetIDCand = 1;
  void clear_targetidcand();
  static const int kTargetIDCandFieldNumber = 1;
  ::google::protobuf::int32 targetidcand() const;
  void set_targetidcand(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PBTargetAssociation_DS_Mass)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double associationmass_;
  ::google::protobuf::int32 targetidcand_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Target_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBTarget

// uint32 sequenceNum = 1;
inline void PBTarget::clear_sequencenum() {
  sequencenum_ = 0u;
}
inline ::google::protobuf::uint32 PBTarget::sequencenum() const {
  // @@protoc_insertion_point(field_get:PBTarget.sequenceNum)
  return sequencenum_;
}
inline void PBTarget::set_sequencenum(::google::protobuf::uint32 value) {
  
  sequencenum_ = value;
  // @@protoc_insertion_point(field_set:PBTarget.sequenceNum)
}

// .PB_Enum_Software enum_Sender_Software = 2;
inline void PBTarget::clear_enum_sender_software() {
  enum_sender_software_ = 0;
}
inline ::PB_Enum_Software PBTarget::enum_sender_software() const {
  // @@protoc_insertion_point(field_get:PBTarget.enum_Sender_Software)
  return static_cast< ::PB_Enum_Software >(enum_sender_software_);
}
inline void PBTarget::set_enum_sender_software(::PB_Enum_Software value) {
  
  enum_sender_software_ = value;
  // @@protoc_insertion_point(field_set:PBTarget.enum_Sender_Software)
}

// repeated .PBTargetPosition listTargetPos = 3;
inline int PBTarget::listtargetpos_size() const {
  return listtargetpos_.size();
}
inline void PBTarget::clear_listtargetpos() {
  listtargetpos_.Clear();
}
inline ::PBTargetPosition* PBTarget::mutable_listtargetpos(int index) {
  // @@protoc_insertion_point(field_mutable:PBTarget.listTargetPos)
  return listtargetpos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::PBTargetPosition >*
PBTarget::mutable_listtargetpos() {
  // @@protoc_insertion_point(field_mutable_list:PBTarget.listTargetPos)
  return &listtargetpos_;
}
inline const ::PBTargetPosition& PBTarget::listtargetpos(int index) const {
  // @@protoc_insertion_point(field_get:PBTarget.listTargetPos)
  return listtargetpos_.Get(index);
}
inline ::PBTargetPosition* PBTarget::add_listtargetpos() {
  // @@protoc_insertion_point(field_add:PBTarget.listTargetPos)
  return listtargetpos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBTargetPosition >&
PBTarget::listtargetpos() const {
  // @@protoc_insertion_point(field_list:PBTarget.listTargetPos)
  return listtargetpos_;
}

// -------------------------------------------------------------------

// PBTargetPosition

// int32 targetID = 1;
inline void PBTargetPosition::clear_targetid() {
  targetid_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::targetid() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.targetID)
  return targetid_;
}
inline void PBTargetPosition::set_targetid(::google::protobuf::int32 value) {
  
  targetid_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.targetID)
}

// .PBAISDynamic aisDynamic = 2;
inline bool PBTargetPosition::has_aisdynamic() const {
  return this != internal_default_instance() && aisdynamic_ != NULL;
}
inline const ::PBAISDynamic& PBTargetPosition::_internal_aisdynamic() const {
  return *aisdynamic_;
}
inline const ::PBAISDynamic& PBTargetPosition::aisdynamic() const {
  const ::PBAISDynamic* p = aisdynamic_;
  // @@protoc_insertion_point(field_get:PBTargetPosition.aisDynamic)
  return p != NULL ? *p : *reinterpret_cast<const ::PBAISDynamic*>(
      &::_PBAISDynamic_default_instance_);
}
inline ::PBAISDynamic* PBTargetPosition::release_aisdynamic() {
  // @@protoc_insertion_point(field_release:PBTargetPosition.aisDynamic)
  
  ::PBAISDynamic* temp = aisdynamic_;
  aisdynamic_ = NULL;
  return temp;
}
inline ::PBAISDynamic* PBTargetPosition::mutable_aisdynamic() {
  
  if (aisdynamic_ == NULL) {
    auto* p = CreateMaybeMessage<::PBAISDynamic>(GetArenaNoVirtual());
    aisdynamic_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PBTargetPosition.aisDynamic)
  return aisdynamic_;
}
inline void PBTargetPosition::set_allocated_aisdynamic(::PBAISDynamic* aisdynamic) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(aisdynamic_);
  }
  if (aisdynamic) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      aisdynamic = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, aisdynamic, submessage_arena);
    }
    
  } else {
    
  }
  aisdynamic_ = aisdynamic;
  // @@protoc_insertion_point(field_set_allocated:PBTargetPosition.aisDynamic)
}

// .PBAISStatic aisStatic = 3;
inline bool PBTargetPosition::has_aisstatic() const {
  return this != internal_default_instance() && aisstatic_ != NULL;
}
inline const ::PBAISStatic& PBTargetPosition::_internal_aisstatic() const {
  return *aisstatic_;
}
inline const ::PBAISStatic& PBTargetPosition::aisstatic() const {
  const ::PBAISStatic* p = aisstatic_;
  // @@protoc_insertion_point(field_get:PBTargetPosition.aisStatic)
  return p != NULL ? *p : *reinterpret_cast<const ::PBAISStatic*>(
      &::_PBAISStatic_default_instance_);
}
inline ::PBAISStatic* PBTargetPosition::release_aisstatic() {
  // @@protoc_insertion_point(field_release:PBTargetPosition.aisStatic)
  
  ::PBAISStatic* temp = aisstatic_;
  aisstatic_ = NULL;
  return temp;
}
inline ::PBAISStatic* PBTargetPosition::mutable_aisstatic() {
  
  if (aisstatic_ == NULL) {
    auto* p = CreateMaybeMessage<::PBAISStatic>(GetArenaNoVirtual());
    aisstatic_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PBTargetPosition.aisStatic)
  return aisstatic_;
}
inline void PBTargetPosition::set_allocated_aisstatic(::PBAISStatic* aisstatic) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(aisstatic_);
  }
  if (aisstatic) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      aisstatic = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, aisstatic, submessage_arena);
    }
    
  } else {
    
  }
  aisstatic_ = aisstatic;
  // @@protoc_insertion_point(field_set_allocated:PBTargetPosition.aisStatic)
}

// .PBAISVoyage aisVoyage = 4;
inline bool PBTargetPosition::has_aisvoyage() const {
  return this != internal_default_instance() && aisvoyage_ != NULL;
}
inline const ::PBAISVoyage& PBTargetPosition::_internal_aisvoyage() const {
  return *aisvoyage_;
}
inline const ::PBAISVoyage& PBTargetPosition::aisvoyage() const {
  const ::PBAISVoyage* p = aisvoyage_;
  // @@protoc_insertion_point(field_get:PBTargetPosition.aisVoyage)
  return p != NULL ? *p : *reinterpret_cast<const ::PBAISVoyage*>(
      &::_PBAISVoyage_default_instance_);
}
inline ::PBAISVoyage* PBTargetPosition::release_aisvoyage() {
  // @@protoc_insertion_point(field_release:PBTargetPosition.aisVoyage)
  
  ::PBAISVoyage* temp = aisvoyage_;
  aisvoyage_ = NULL;
  return temp;
}
inline ::PBAISVoyage* PBTargetPosition::mutable_aisvoyage() {
  
  if (aisvoyage_ == NULL) {
    auto* p = CreateMaybeMessage<::PBAISVoyage>(GetArenaNoVirtual());
    aisvoyage_ = p;
  }
  // @@protoc_insertion_point(field_mutable:PBTargetPosition.aisVoyage)
  return aisvoyage_;
}
inline void PBTargetPosition::set_allocated_aisvoyage(::PBAISVoyage* aisvoyage) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(aisvoyage_);
  }
  if (aisvoyage) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      aisvoyage = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, aisvoyage, submessage_arena);
    }
    
  } else {
    
  }
  aisvoyage_ = aisvoyage;
  // @@protoc_insertion_point(field_set_allocated:PBTargetPosition.aisVoyage)
}

// .PB_Enum_TargetInfo_Type enum_targetInfoType = 5;
inline void PBTargetPosition::clear_enum_targetinfotype() {
  enum_targetinfotype_ = 0;
}
inline ::PB_Enum_TargetInfo_Type PBTargetPosition::enum_targetinfotype() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.enum_targetInfoType)
  return static_cast< ::PB_Enum_TargetInfo_Type >(enum_targetinfotype_);
}
inline void PBTargetPosition::set_enum_targetinfotype(::PB_Enum_TargetInfo_Type value) {
  
  enum_targetinfotype_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.enum_targetInfoType)
}

// .PB_Enum_TargetInfo_Source enum_targetInfoSource = 6;
inline void PBTargetPosition::clear_enum_targetinfosource() {
  enum_targetinfosource_ = 0;
}
inline ::PB_Enum_TargetInfo_Source PBTargetPosition::enum_targetinfosource() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.enum_targetInfoSource)
  return static_cast< ::PB_Enum_TargetInfo_Source >(enum_targetinfosource_);
}
inline void PBTargetPosition::set_enum_targetinfosource(::PB_Enum_TargetInfo_Source value) {
  
  enum_targetinfosource_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.enum_targetInfoSource)
}

// .PB_Enum_TargetID_Type enum_TargetIDOrig_Type = 7;
inline void PBTargetPosition::clear_enum_targetidorig_type() {
  enum_targetidorig_type_ = 0;
}
inline ::PB_Enum_TargetID_Type PBTargetPosition::enum_targetidorig_type() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.enum_TargetIDOrig_Type)
  return static_cast< ::PB_Enum_TargetID_Type >(enum_targetidorig_type_);
}
inline void PBTargetPosition::set_enum_targetidorig_type(::PB_Enum_TargetID_Type value) {
  
  enum_targetidorig_type_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.enum_TargetIDOrig_Type)
}

// int32 targetIDOrig = 8;
inline void PBTargetPosition::clear_targetidorig() {
  targetidorig_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::targetidorig() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.targetIDOrig)
  return targetidorig_;
}
inline void PBTargetPosition::set_targetidorig(::google::protobuf::int32 value) {
  
  targetidorig_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.targetIDOrig)
}

// string countryName = 9;
inline void PBTargetPosition::clear_countryname() {
  countryname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBTargetPosition::countryname() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.countryName)
  return countryname_.GetNoArena();
}
inline void PBTargetPosition::set_countryname(const ::std::string& value) {
  
  countryname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PBTargetPosition.countryName)
}
#if LANG_CXX11
inline void PBTargetPosition::set_countryname(::std::string&& value) {
  
  countryname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PBTargetPosition.countryName)
}
#endif
inline void PBTargetPosition::set_countryname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  countryname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PBTargetPosition.countryName)
}
inline void PBTargetPosition::set_countryname(const char* value, size_t size) {
  
  countryname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PBTargetPosition.countryName)
}
inline ::std::string* PBTargetPosition::mutable_countryname() {
  
  // @@protoc_insertion_point(field_mutable:PBTargetPosition.countryName)
  return countryname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBTargetPosition::release_countryname() {
  // @@protoc_insertion_point(field_release:PBTargetPosition.countryName)
  
  return countryname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBTargetPosition::set_allocated_countryname(::std::string* countryname) {
  if (countryname != NULL) {
    
  } else {
    
  }
  countryname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), countryname);
  // @@protoc_insertion_point(field_set_allocated:PBTargetPosition.countryName)
}

// .PB_Enum_Aggregated_AIS_Ship_Type aggregatedAISShipType = 10;
inline void PBTargetPosition::clear_aggregatedaisshiptype() {
  aggregatedaisshiptype_ = 0;
}
inline ::PB_Enum_Aggregated_AIS_Ship_Type PBTargetPosition::aggregatedaisshiptype() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.aggregatedAISShipType)
  return static_cast< ::PB_Enum_Aggregated_AIS_Ship_Type >(aggregatedaisshiptype_);
}
inline void PBTargetPosition::set_aggregatedaisshiptype(::PB_Enum_Aggregated_AIS_Ship_Type value) {
  
  aggregatedaisshiptype_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.aggregatedAISShipType)
}

// int32 cargoType = 11;
inline void PBTargetPosition::clear_cargotype() {
  cargotype_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::cargotype() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.cargoType)
  return cargotype_;
}
inline void PBTargetPosition::set_cargotype(::google::protobuf::int32 value) {
  
  cargotype_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.cargoType)
}

// bool isDangerShip = 13;
inline void PBTargetPosition::clear_isdangership() {
  isdangership_ = false;
}
inline bool PBTargetPosition::isdangership() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.isDangerShip)
  return isdangership_;
}
inline void PBTargetPosition::set_isdangership(bool value) {
  
  isdangership_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.isDangerShip)
}

// uint32 lastAssocUsingDSCombinationUTCTime = 14;
inline void PBTargetPosition::clear_lastassocusingdscombinationutctime() {
  lastassocusingdscombinationutctime_ = 0u;
}
inline ::google::protobuf::uint32 PBTargetPosition::lastassocusingdscombinationutctime() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.lastAssocUsingDSCombinationUTCTime)
  return lastassocusingdscombinationutctime_;
}
inline void PBTargetPosition::set_lastassocusingdscombinationutctime(::google::protobuf::uint32 value) {
  
  lastassocusingdscombinationutctime_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.lastAssocUsingDSCombinationUTCTime)
}

// int32 beidouID = 15;
inline void PBTargetPosition::clear_beidouid() {
  beidouid_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::beidouid() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.beidouID)
  return beidouid_;
}
inline void PBTargetPosition::set_beidouid(::google::protobuf::int32 value) {
  
  beidouid_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.beidouID)
}

// int32 haijianID = 16;
inline void PBTargetPosition::clear_haijianid() {
  haijianid_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::haijianid() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.haijianID)
  return haijianid_;
}
inline void PBTargetPosition::set_haijianid(::google::protobuf::int32 value) {
  
  haijianid_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.haijianID)
}

// int32 argosAndMarineSatID = 17;
inline void PBTargetPosition::clear_argosandmarinesatid() {
  argosandmarinesatid_ = 0;
}
inline ::google::protobuf::int32 PBTargetPosition::argosandmarinesatid() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.argosAndMarineSatID)
  return argosandmarinesatid_;
}
inline void PBTargetPosition::set_argosandmarinesatid(::google::protobuf::int32 value) {
  
  argosandmarinesatid_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.argosAndMarineSatID)
}

// .PB_Enum_Target_ThreatLevel enum_TargetThreadLevel = 31;
inline void PBTargetPosition::clear_enum_targetthreadlevel() {
  enum_targetthreadlevel_ = 0;
}
inline ::PB_Enum_Target_ThreatLevel PBTargetPosition::enum_targetthreadlevel() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.enum_TargetThreadLevel)
  return static_cast< ::PB_Enum_Target_ThreatLevel >(enum_targetthreadlevel_);
}
inline void PBTargetPosition::set_enum_targetthreadlevel(::PB_Enum_Target_ThreatLevel value) {
  
  enum_targetthreadlevel_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.enum_TargetThreadLevel)
}

// bool isInterestTarget = 32;
inline void PBTargetPosition::clear_isinteresttarget() {
  isinteresttarget_ = false;
}
inline bool PBTargetPosition::isinteresttarget() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.isInterestTarget)
  return isinteresttarget_;
}
inline void PBTargetPosition::set_isinteresttarget(bool value) {
  
  isinteresttarget_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.isInterestTarget)
}

// .PB_Enum_Target_XGSCustomizedThreatLevel enum_XGSCustomizedTargetThreadLevel = 33;
inline void PBTargetPosition::clear_enum_xgscustomizedtargetthreadlevel() {
  enum_xgscustomizedtargetthreadlevel_ = 0;
}
inline ::PB_Enum_Target_XGSCustomizedThreatLevel PBTargetPosition::enum_xgscustomizedtargetthreadlevel() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.enum_XGSCustomizedTargetThreadLevel)
  return static_cast< ::PB_Enum_Target_XGSCustomizedThreatLevel >(enum_xgscustomizedtargetthreadlevel_);
}
inline void PBTargetPosition::set_enum_xgscustomizedtargetthreadlevel(::PB_Enum_Target_XGSCustomizedThreatLevel value) {
  
  enum_xgscustomizedtargetthreadlevel_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.enum_XGSCustomizedTargetThreadLevel)
}

// bool isWarShip = 34;
inline void PBTargetPosition::clear_iswarship() {
  iswarship_ = false;
}
inline bool PBTargetPosition::iswarship() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.isWarShip)
  return iswarship_;
}
inline void PBTargetPosition::set_iswarship(bool value) {
  
  iswarship_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.isWarShip)
}

// bool isLawEnforceShip = 35;
inline void PBTargetPosition::clear_islawenforceship() {
  islawenforceship_ = false;
}
inline bool PBTargetPosition::islawenforceship() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.isLawEnforceShip)
  return islawenforceship_;
}
inline void PBTargetPosition::set_islawenforceship(bool value) {
  
  islawenforceship_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.isLawEnforceShip)
}

// bool isChinese = 36;
inline void PBTargetPosition::clear_ischinese() {
  ischinese_ = false;
}
inline bool PBTargetPosition::ischinese() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.isChinese)
  return ischinese_;
}
inline void PBTargetPosition::set_ischinese(bool value) {
  
  ischinese_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.isChinese)
}

// uint32 zoneEntryTimes = 37;
inline void PBTargetPosition::clear_zoneentrytimes() {
  zoneentrytimes_ = 0u;
}
inline ::google::protobuf::uint32 PBTargetPosition::zoneentrytimes() const {
  // @@protoc_insertion_point(field_get:PBTargetPosition.zoneEntryTimes)
  return zoneentrytimes_;
}
inline void PBTargetPosition::set_zoneentrytimes(::google::protobuf::uint32 value) {
  
  zoneentrytimes_ = value;
  // @@protoc_insertion_point(field_set:PBTargetPosition.zoneEntryTimes)
}

// -------------------------------------------------------------------

// PBTargetAssociation_DS_Mass

// int32 targetIDCand = 1;
inline void PBTargetAssociation_DS_Mass::clear_targetidcand() {
  targetidcand_ = 0;
}
inline ::google::protobuf::int32 PBTargetAssociation_DS_Mass::targetidcand() const {
  // @@protoc_insertion_point(field_get:PBTargetAssociation_DS_Mass.targetIDCand)
  return targetidcand_;
}
inline void PBTargetAssociation_DS_Mass::set_targetidcand(::google::protobuf::int32 value) {
  
  targetidcand_ = value;
  // @@protoc_insertion_point(field_set:PBTargetAssociation_DS_Mass.targetIDCand)
}

// double associationMass = 2;
inline void PBTargetAssociation_DS_Mass::clear_associationmass() {
  associationmass_ = 0;
}
inline double PBTargetAssociation_DS_Mass::associationmass() const {
  // @@protoc_insertion_point(field_get:PBTargetAssociation_DS_Mass.associationMass)
  return associationmass_;
}
inline void PBTargetAssociation_DS_Mass::set_associationmass(double value) {
  
  associationmass_ = value;
  // @@protoc_insertion_point(field_set:PBTargetAssociation_DS_Mass.associationMass)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Target_2eproto
