// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AISData.proto

#ifndef PROTOBUF_AISData_2eproto__INCLUDED
#define PROTOBUF_AISData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_AISData_2eproto();
void protobuf_InitDefaults_AISData_2eproto();
void protobuf_AssignDesc_AISData_2eproto();
void protobuf_ShutdownFile_AISData_2eproto();

class PBAISDynamic;
class PBAISStatic;
class PBAISVoyage;

enum PB_Enum_AIS_Device_Class_Type {
  EV_AISDeviceClassType_ClassA = 0,
  EV_AISDeviceClassType_ClassB = 1,
  PB_Enum_AIS_Device_Class_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PB_Enum_AIS_Device_Class_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PB_Enum_AIS_Device_Class_Type_IsValid(int value);
const PB_Enum_AIS_Device_Class_Type PB_Enum_AIS_Device_Class_Type_MIN = EV_AISDeviceClassType_ClassA;
const PB_Enum_AIS_Device_Class_Type PB_Enum_AIS_Device_Class_Type_MAX = EV_AISDeviceClassType_ClassB;
const int PB_Enum_AIS_Device_Class_Type_ARRAYSIZE = PB_Enum_AIS_Device_Class_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* PB_Enum_AIS_Device_Class_Type_descriptor();
inline const ::std::string& PB_Enum_AIS_Device_Class_Type_Name(PB_Enum_AIS_Device_Class_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    PB_Enum_AIS_Device_Class_Type_descriptor(), value);
}
inline bool PB_Enum_AIS_Device_Class_Type_Parse(
    const ::std::string& name, PB_Enum_AIS_Device_Class_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PB_Enum_AIS_Device_Class_Type>(
    PB_Enum_AIS_Device_Class_Type_descriptor(), name, value);
}
enum PB_Enum_AIS_Commum_State {
  EV_AISCommumState_NA = 0,
  EV_AISCommumState_SOTDMA = 1,
  EV_AISCommumState_ITDMA = 2,
  PB_Enum_AIS_Commum_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PB_Enum_AIS_Commum_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PB_Enum_AIS_Commum_State_IsValid(int value);
const PB_Enum_AIS_Commum_State PB_Enum_AIS_Commum_State_MIN = EV_AISCommumState_NA;
const PB_Enum_AIS_Commum_State PB_Enum_AIS_Commum_State_MAX = EV_AISCommumState_ITDMA;
const int PB_Enum_AIS_Commum_State_ARRAYSIZE = PB_Enum_AIS_Commum_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* PB_Enum_AIS_Commum_State_descriptor();
inline const ::std::string& PB_Enum_AIS_Commum_State_Name(PB_Enum_AIS_Commum_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    PB_Enum_AIS_Commum_State_descriptor(), value);
}
inline bool PB_Enum_AIS_Commum_State_Parse(
    const ::std::string& name, PB_Enum_AIS_Commum_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PB_Enum_AIS_Commum_State>(
    PB_Enum_AIS_Commum_State_descriptor(), name, value);
}
enum PB_Enum_AIS_Pos_Accuracy {
  EV_AISPosAccuracy_NA = 0,
  EV_AISPosAccuracy_Low = 1,
  EV_AISPosAccuracy_High = 2,
  PB_Enum_AIS_Pos_Accuracy_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PB_Enum_AIS_Pos_Accuracy_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PB_Enum_AIS_Pos_Accuracy_IsValid(int value);
const PB_Enum_AIS_Pos_Accuracy PB_Enum_AIS_Pos_Accuracy_MIN = EV_AISPosAccuracy_NA;
const PB_Enum_AIS_Pos_Accuracy PB_Enum_AIS_Pos_Accuracy_MAX = EV_AISPosAccuracy_High;
const int PB_Enum_AIS_Pos_Accuracy_ARRAYSIZE = PB_Enum_AIS_Pos_Accuracy_MAX + 1;

const ::google::protobuf::EnumDescriptor* PB_Enum_AIS_Pos_Accuracy_descriptor();
inline const ::std::string& PB_Enum_AIS_Pos_Accuracy_Name(PB_Enum_AIS_Pos_Accuracy value) {
  return ::google::protobuf::internal::NameOfEnum(
    PB_Enum_AIS_Pos_Accuracy_descriptor(), value);
}
inline bool PB_Enum_AIS_Pos_Accuracy_Parse(
    const ::std::string& name, PB_Enum_AIS_Pos_Accuracy* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PB_Enum_AIS_Pos_Accuracy>(
    PB_Enum_AIS_Pos_Accuracy_descriptor(), name, value);
}
enum PB_Enum_AIS_Fixing_Device {
  EV_AISFixingDevice_NA = 0,
  EV_AISFixingDevice_GPS = 1,
  EV_AISFixingDevice_GLONASS = 2,
  EV_AISFixingDevice_CombinedGPSGLONASS = 3,
  EV_AISFixingDevice_Loran_C = 4,
  EV_AISFixingDevice_Chayka = 5,
  EV_AISFixingDevice_IntegratedNavSys = 6,
  EV_AISFixingDevice_Surveyed = 7,
  EV_AISFixingDevice_Galileo = 8,
  EV_AISFixingDevice_Beidou = 9,
  EV_AISFixingDevice_Observation = 10,
  EV_AISFixingDevice_InternalGNSS = 15,
  PB_Enum_AIS_Fixing_Device_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PB_Enum_AIS_Fixing_Device_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PB_Enum_AIS_Fixing_Device_IsValid(int value);
const PB_Enum_AIS_Fixing_Device PB_Enum_AIS_Fixing_Device_MIN = EV_AISFixingDevice_NA;
const PB_Enum_AIS_Fixing_Device PB_Enum_AIS_Fixing_Device_MAX = EV_AISFixingDevice_InternalGNSS;
const int PB_Enum_AIS_Fixing_Device_ARRAYSIZE = PB_Enum_AIS_Fixing_Device_MAX + 1;

const ::google::protobuf::EnumDescriptor* PB_Enum_AIS_Fixing_Device_descriptor();
inline const ::std::string& PB_Enum_AIS_Fixing_Device_Name(PB_Enum_AIS_Fixing_Device value) {
  return ::google::protobuf::internal::NameOfEnum(
    PB_Enum_AIS_Fixing_Device_descriptor(), value);
}
inline bool PB_Enum_AIS_Fixing_Device_Parse(
    const ::std::string& name, PB_Enum_AIS_Fixing_Device* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PB_Enum_AIS_Fixing_Device>(
    PB_Enum_AIS_Fixing_Device_descriptor(), name, value);
}
// ===================================================================

class PBAISDynamic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBAISDynamic) */ {
 public:
  PBAISDynamic();
  virtual ~PBAISDynamic();

  PBAISDynamic(const PBAISDynamic& from);

  inline PBAISDynamic& operator=(const PBAISDynamic& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAISDynamic& default_instance();

  static const PBAISDynamic* internal_default_instance();

  void Swap(PBAISDynamic* other);

  // implements Message ----------------------------------------------

  inline PBAISDynamic* New() const { return New(NULL); }

  PBAISDynamic* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBAISDynamic& from);
  void MergeFrom(const PBAISDynamic& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBAISDynamic* other);
  void UnsafeMergeFrom(const PBAISDynamic& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 utcTimeStamp = 1;
  void clear_utctimestamp();
  static const int kUtcTimeStampFieldNumber = 1;
  ::google::protobuf::uint32 utctimestamp() const;
  void set_utctimestamp(::google::protobuf::uint32 value);

  // optional int32 MMSI = 2;
  void clear_mmsi();
  static const int kMMSIFieldNumber = 2;
  ::google::protobuf::int32 mmsi() const;
  void set_mmsi(::google::protobuf::int32 value);

  // optional int32 intLongitudeX60W = 3;
  void clear_intlongitudex60w();
  static const int kIntLongitudeX60WFieldNumber = 3;
  ::google::protobuf::int32 intlongitudex60w() const;
  void set_intlongitudex60w(::google::protobuf::int32 value);

  // optional int32 intLatitudeX60W = 4;
  void clear_intlatitudex60w();
  static const int kIntLatitudeX60WFieldNumber = 4;
  ::google::protobuf::int32 intlatitudex60w() const;
  void set_intlatitudex60w(::google::protobuf::int32 value);

  // optional uint32 COGDegreeX10 = 5;
  void clear_cogdegreex10();
  static const int kCOGDegreeX10FieldNumber = 5;
  ::google::protobuf::uint32 cogdegreex10() const;
  void set_cogdegreex10(::google::protobuf::uint32 value);

  // optional uint32 headingDegree = 6;
  void clear_headingdegree();
  static const int kHeadingDegreeFieldNumber = 6;
  ::google::protobuf::uint32 headingdegree() const;
  void set_headingdegree(::google::protobuf::uint32 value);

  // optional uint32 SOGKnotsX10 = 7;
  void clear_sogknotsx10();
  static const int kSOGKnotsX10FieldNumber = 7;
  ::google::protobuf::uint32 sogknotsx10() const;
  void set_sogknotsx10(::google::protobuf::uint32 value);

  // optional uint32 Status = 8;
  void clear_status();
  static const int kStatusFieldNumber = 8;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // optional int32 ROT_Sensor_DegreePerMinute = 9;
  void clear_rot_sensor_degreeperminute();
  static const int kROTSensorDegreePerMinuteFieldNumber = 9;
  ::google::protobuf::int32 rot_sensor_degreeperminute() const;
  void set_rot_sensor_degreeperminute(::google::protobuf::int32 value);

  // optional .PB_Enum_AIS_Pos_Accuracy enum_PosAccuracy = 10;
  void clear_enum_posaccuracy();
  static const int kEnumPosAccuracyFieldNumber = 10;
  ::PB_Enum_AIS_Pos_Accuracy enum_posaccuracy() const;
  void set_enum_posaccuracy(::PB_Enum_AIS_Pos_Accuracy value);

  // optional .PB_Enum_AIS_Commum_State enum_CommunState = 11;
  void clear_enum_communstate();
  static const int kEnumCommunStateFieldNumber = 11;
  ::PB_Enum_AIS_Commum_State enum_communstate() const;
  void set_enum_communstate(::PB_Enum_AIS_Commum_State value);

  // @@protoc_insertion_point(class_scope:PBAISDynamic)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 utctimestamp_;
  ::google::protobuf::int32 mmsi_;
  ::google::protobuf::int32 intlongitudex60w_;
  ::google::protobuf::int32 intlatitudex60w_;
  ::google::protobuf::uint32 cogdegreex10_;
  ::google::protobuf::uint32 headingdegree_;
  ::google::protobuf::uint32 sogknotsx10_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::int32 rot_sensor_degreeperminute_;
  int enum_posaccuracy_;
  int enum_communstate_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_AISData_2eproto_impl();
  friend void  protobuf_AddDesc_AISData_2eproto_impl();
  friend void protobuf_AssignDesc_AISData_2eproto();
  friend void protobuf_ShutdownFile_AISData_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBAISDynamic> PBAISDynamic_default_instance_;

// -------------------------------------------------------------------

class PBAISStatic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBAISStatic) */ {
 public:
  PBAISStatic();
  virtual ~PBAISStatic();

  PBAISStatic(const PBAISStatic& from);

  inline PBAISStatic& operator=(const PBAISStatic& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAISStatic& default_instance();

  static const PBAISStatic* internal_default_instance();

  void Swap(PBAISStatic* other);

  // implements Message ----------------------------------------------

  inline PBAISStatic* New() const { return New(NULL); }

  PBAISStatic* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBAISStatic& from);
  void MergeFrom(const PBAISStatic& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBAISStatic* other);
  void UnsafeMergeFrom(const PBAISStatic& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 MMSI = 1;
  void clear_mmsi();
  static const int kMMSIFieldNumber = 1;
  ::google::protobuf::int32 mmsi() const;
  void set_mmsi(::google::protobuf::int32 value);

  // optional uint32 utcTimeStamp = 2;
  void clear_utctimestamp();
  static const int kUtcTimeStampFieldNumber = 2;
  ::google::protobuf::uint32 utctimestamp() const;
  void set_utctimestamp(::google::protobuf::uint32 value);

  // optional int32 shipType_AIS = 3;
  void clear_shiptype_ais();
  static const int kShipTypeAISFieldNumber = 3;
  ::google::protobuf::int32 shiptype_ais() const;
  void set_shiptype_ais(::google::protobuf::int32 value);

  // optional uint32 IMO = 4;
  void clear_imo();
  static const int kIMOFieldNumber = 4;
  ::google::protobuf::uint32 imo() const;
  void set_imo(::google::protobuf::uint32 value);

  // optional string shipName = 5;
  void clear_shipname();
  static const int kShipNameFieldNumber = 5;
  const ::std::string& shipname() const;
  void set_shipname(const ::std::string& value);
  void set_shipname(const char* value);
  void set_shipname(const char* value, size_t size);
  ::std::string* mutable_shipname();
  ::std::string* release_shipname();
  void set_allocated_shipname(::std::string* shipname);

  // optional string callSign = 6;
  void clear_callsign();
  static const int kCallSignFieldNumber = 6;
  const ::std::string& callsign() const;
  void set_callsign(const ::std::string& value);
  void set_callsign(const char* value);
  void set_callsign(const char* value, size_t size);
  ::std::string* mutable_callsign();
  ::std::string* release_callsign();
  void set_allocated_callsign(::std::string* callsign);

  // optional uint32 breadthMeters = 7;
  void clear_breadthmeters();
  static const int kBreadthMetersFieldNumber = 7;
  ::google::protobuf::uint32 breadthmeters() const;
  void set_breadthmeters(::google::protobuf::uint32 value);

  // optional uint32 lenghMeters = 8;
  void clear_lenghmeters();
  static const int kLenghMetersFieldNumber = 8;
  ::google::protobuf::uint32 lenghmeters() const;
  void set_lenghmeters(::google::protobuf::uint32 value);

  // optional .PB_Enum_AIS_Fixing_Device fixingDevice = 9;
  void clear_fixingdevice();
  static const int kFixingDeviceFieldNumber = 9;
  ::PB_Enum_AIS_Fixing_Device fixingdevice() const;
  void set_fixingdevice(::PB_Enum_AIS_Fixing_Device value);

  // @@protoc_insertion_point(class_scope:PBAISStatic)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr shipname_;
  ::google::protobuf::internal::ArenaStringPtr callsign_;
  ::google::protobuf::int32 mmsi_;
  ::google::protobuf::uint32 utctimestamp_;
  ::google::protobuf::int32 shiptype_ais_;
  ::google::protobuf::uint32 imo_;
  ::google::protobuf::uint32 breadthmeters_;
  ::google::protobuf::uint32 lenghmeters_;
  int fixingdevice_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_AISData_2eproto_impl();
  friend void  protobuf_AddDesc_AISData_2eproto_impl();
  friend void protobuf_AssignDesc_AISData_2eproto();
  friend void protobuf_ShutdownFile_AISData_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBAISStatic> PBAISStatic_default_instance_;

// -------------------------------------------------------------------

class PBAISVoyage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBAISVoyage) */ {
 public:
  PBAISVoyage();
  virtual ~PBAISVoyage();

  PBAISVoyage(const PBAISVoyage& from);

  inline PBAISVoyage& operator=(const PBAISVoyage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBAISVoyage& default_instance();

  static const PBAISVoyage* internal_default_instance();

  void Swap(PBAISVoyage* other);

  // implements Message ----------------------------------------------

  inline PBAISVoyage* New() const { return New(NULL); }

  PBAISVoyage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBAISVoyage& from);
  void MergeFrom(const PBAISVoyage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBAISVoyage* other);
  void UnsafeMergeFrom(const PBAISVoyage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 MMSI = 1;
  void clear_mmsi();
  static const int kMMSIFieldNumber = 1;
  ::google::protobuf::int32 mmsi() const;
  void set_mmsi(::google::protobuf::int32 value);

  // optional uint32 utcTimeStamp = 2;
  void clear_utctimestamp();
  static const int kUtcTimeStampFieldNumber = 2;
  ::google::protobuf::uint32 utctimestamp() const;
  void set_utctimestamp(::google::protobuf::uint32 value);

  // optional string destination = 3;
  void clear_destination();
  static const int kDestinationFieldNumber = 3;
  const ::std::string& destination() const;
  void set_destination(const ::std::string& value);
  void set_destination(const char* value);
  void set_destination(const char* value, size_t size);
  ::std::string* mutable_destination();
  ::std::string* release_destination();
  void set_allocated_destination(::std::string* destination);

  // optional string ETA = 4;
  void clear_eta();
  static const int kETAFieldNumber = 4;
  const ::std::string& eta() const;
  void set_eta(const ::std::string& value);
  void set_eta(const char* value);
  void set_eta(const char* value, size_t size);
  ::std::string* mutable_eta();
  ::std::string* release_eta();
  void set_allocated_eta(::std::string* eta);

  // optional uint32 draftMetersX10 = 5;
  void clear_draftmetersx10();
  static const int kDraftMetersX10FieldNumber = 5;
  ::google::protobuf::uint32 draftmetersx10() const;
  void set_draftmetersx10(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PBAISVoyage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr destination_;
  ::google::protobuf::internal::ArenaStringPtr eta_;
  ::google::protobuf::int32 mmsi_;
  ::google::protobuf::uint32 utctimestamp_;
  ::google::protobuf::uint32 draftmetersx10_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_AISData_2eproto_impl();
  friend void  protobuf_AddDesc_AISData_2eproto_impl();
  friend void protobuf_AssignDesc_AISData_2eproto();
  friend void protobuf_ShutdownFile_AISData_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBAISVoyage> PBAISVoyage_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PBAISDynamic

// optional uint32 utcTimeStamp = 1;
inline void PBAISDynamic::clear_utctimestamp() {
  utctimestamp_ = 0u;
}
inline ::google::protobuf::uint32 PBAISDynamic::utctimestamp() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.utcTimeStamp)
  return utctimestamp_;
}
inline void PBAISDynamic::set_utctimestamp(::google::protobuf::uint32 value) {
  
  utctimestamp_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.utcTimeStamp)
}

// optional int32 MMSI = 2;
inline void PBAISDynamic::clear_mmsi() {
  mmsi_ = 0;
}
inline ::google::protobuf::int32 PBAISDynamic::mmsi() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.MMSI)
  return mmsi_;
}
inline void PBAISDynamic::set_mmsi(::google::protobuf::int32 value) {
  
  mmsi_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.MMSI)
}

// optional int32 intLongitudeX60W = 3;
inline void PBAISDynamic::clear_intlongitudex60w() {
  intlongitudex60w_ = 0;
}
inline ::google::protobuf::int32 PBAISDynamic::intlongitudex60w() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.intLongitudeX60W)
  return intlongitudex60w_;
}
inline void PBAISDynamic::set_intlongitudex60w(::google::protobuf::int32 value) {
  
  intlongitudex60w_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.intLongitudeX60W)
}

// optional int32 intLatitudeX60W = 4;
inline void PBAISDynamic::clear_intlatitudex60w() {
  intlatitudex60w_ = 0;
}
inline ::google::protobuf::int32 PBAISDynamic::intlatitudex60w() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.intLatitudeX60W)
  return intlatitudex60w_;
}
inline void PBAISDynamic::set_intlatitudex60w(::google::protobuf::int32 value) {
  
  intlatitudex60w_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.intLatitudeX60W)
}

// optional uint32 COGDegreeX10 = 5;
inline void PBAISDynamic::clear_cogdegreex10() {
  cogdegreex10_ = 0u;
}
inline ::google::protobuf::uint32 PBAISDynamic::cogdegreex10() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.COGDegreeX10)
  return cogdegreex10_;
}
inline void PBAISDynamic::set_cogdegreex10(::google::protobuf::uint32 value) {
  
  cogdegreex10_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.COGDegreeX10)
}

// optional uint32 headingDegree = 6;
inline void PBAISDynamic::clear_headingdegree() {
  headingdegree_ = 0u;
}
inline ::google::protobuf::uint32 PBAISDynamic::headingdegree() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.headingDegree)
  return headingdegree_;
}
inline void PBAISDynamic::set_headingdegree(::google::protobuf::uint32 value) {
  
  headingdegree_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.headingDegree)
}

// optional uint32 SOGKnotsX10 = 7;
inline void PBAISDynamic::clear_sogknotsx10() {
  sogknotsx10_ = 0u;
}
inline ::google::protobuf::uint32 PBAISDynamic::sogknotsx10() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.SOGKnotsX10)
  return sogknotsx10_;
}
inline void PBAISDynamic::set_sogknotsx10(::google::protobuf::uint32 value) {
  
  sogknotsx10_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.SOGKnotsX10)
}

// optional uint32 Status = 8;
inline void PBAISDynamic::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 PBAISDynamic::status() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.Status)
  return status_;
}
inline void PBAISDynamic::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.Status)
}

// optional int32 ROT_Sensor_DegreePerMinute = 9;
inline void PBAISDynamic::clear_rot_sensor_degreeperminute() {
  rot_sensor_degreeperminute_ = 0;
}
inline ::google::protobuf::int32 PBAISDynamic::rot_sensor_degreeperminute() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.ROT_Sensor_DegreePerMinute)
  return rot_sensor_degreeperminute_;
}
inline void PBAISDynamic::set_rot_sensor_degreeperminute(::google::protobuf::int32 value) {
  
  rot_sensor_degreeperminute_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.ROT_Sensor_DegreePerMinute)
}

// optional .PB_Enum_AIS_Pos_Accuracy enum_PosAccuracy = 10;
inline void PBAISDynamic::clear_enum_posaccuracy() {
  enum_posaccuracy_ = 0;
}
inline ::PB_Enum_AIS_Pos_Accuracy PBAISDynamic::enum_posaccuracy() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.enum_PosAccuracy)
  return static_cast< ::PB_Enum_AIS_Pos_Accuracy >(enum_posaccuracy_);
}
inline void PBAISDynamic::set_enum_posaccuracy(::PB_Enum_AIS_Pos_Accuracy value) {
  
  enum_posaccuracy_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.enum_PosAccuracy)
}

// optional .PB_Enum_AIS_Commum_State enum_CommunState = 11;
inline void PBAISDynamic::clear_enum_communstate() {
  enum_communstate_ = 0;
}
inline ::PB_Enum_AIS_Commum_State PBAISDynamic::enum_communstate() const {
  // @@protoc_insertion_point(field_get:PBAISDynamic.enum_CommunState)
  return static_cast< ::PB_Enum_AIS_Commum_State >(enum_communstate_);
}
inline void PBAISDynamic::set_enum_communstate(::PB_Enum_AIS_Commum_State value) {
  
  enum_communstate_ = value;
  // @@protoc_insertion_point(field_set:PBAISDynamic.enum_CommunState)
}

inline const PBAISDynamic* PBAISDynamic::internal_default_instance() {
  return &PBAISDynamic_default_instance_.get();
}
// -------------------------------------------------------------------

// PBAISStatic

// optional int32 MMSI = 1;
inline void PBAISStatic::clear_mmsi() {
  mmsi_ = 0;
}
inline ::google::protobuf::int32 PBAISStatic::mmsi() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.MMSI)
  return mmsi_;
}
inline void PBAISStatic::set_mmsi(::google::protobuf::int32 value) {
  
  mmsi_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.MMSI)
}

// optional uint32 utcTimeStamp = 2;
inline void PBAISStatic::clear_utctimestamp() {
  utctimestamp_ = 0u;
}
inline ::google::protobuf::uint32 PBAISStatic::utctimestamp() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.utcTimeStamp)
  return utctimestamp_;
}
inline void PBAISStatic::set_utctimestamp(::google::protobuf::uint32 value) {
  
  utctimestamp_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.utcTimeStamp)
}

// optional int32 shipType_AIS = 3;
inline void PBAISStatic::clear_shiptype_ais() {
  shiptype_ais_ = 0;
}
inline ::google::protobuf::int32 PBAISStatic::shiptype_ais() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.shipType_AIS)
  return shiptype_ais_;
}
inline void PBAISStatic::set_shiptype_ais(::google::protobuf::int32 value) {
  
  shiptype_ais_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.shipType_AIS)
}

// optional uint32 IMO = 4;
inline void PBAISStatic::clear_imo() {
  imo_ = 0u;
}
inline ::google::protobuf::uint32 PBAISStatic::imo() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.IMO)
  return imo_;
}
inline void PBAISStatic::set_imo(::google::protobuf::uint32 value) {
  
  imo_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.IMO)
}

// optional string shipName = 5;
inline void PBAISStatic::clear_shipname() {
  shipname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBAISStatic::shipname() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.shipName)
  return shipname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISStatic::set_shipname(const ::std::string& value) {
  
  shipname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PBAISStatic.shipName)
}
inline void PBAISStatic::set_shipname(const char* value) {
  
  shipname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PBAISStatic.shipName)
}
inline void PBAISStatic::set_shipname(const char* value, size_t size) {
  
  shipname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PBAISStatic.shipName)
}
inline ::std::string* PBAISStatic::mutable_shipname() {
  
  // @@protoc_insertion_point(field_mutable:PBAISStatic.shipName)
  return shipname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBAISStatic::release_shipname() {
  // @@protoc_insertion_point(field_release:PBAISStatic.shipName)
  
  return shipname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISStatic::set_allocated_shipname(::std::string* shipname) {
  if (shipname != NULL) {
    
  } else {
    
  }
  shipname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shipname);
  // @@protoc_insertion_point(field_set_allocated:PBAISStatic.shipName)
}

// optional string callSign = 6;
inline void PBAISStatic::clear_callsign() {
  callsign_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBAISStatic::callsign() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.callSign)
  return callsign_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISStatic::set_callsign(const ::std::string& value) {
  
  callsign_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PBAISStatic.callSign)
}
inline void PBAISStatic::set_callsign(const char* value) {
  
  callsign_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PBAISStatic.callSign)
}
inline void PBAISStatic::set_callsign(const char* value, size_t size) {
  
  callsign_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PBAISStatic.callSign)
}
inline ::std::string* PBAISStatic::mutable_callsign() {
  
  // @@protoc_insertion_point(field_mutable:PBAISStatic.callSign)
  return callsign_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBAISStatic::release_callsign() {
  // @@protoc_insertion_point(field_release:PBAISStatic.callSign)
  
  return callsign_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISStatic::set_allocated_callsign(::std::string* callsign) {
  if (callsign != NULL) {
    
  } else {
    
  }
  callsign_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), callsign);
  // @@protoc_insertion_point(field_set_allocated:PBAISStatic.callSign)
}

// optional uint32 breadthMeters = 7;
inline void PBAISStatic::clear_breadthmeters() {
  breadthmeters_ = 0u;
}
inline ::google::protobuf::uint32 PBAISStatic::breadthmeters() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.breadthMeters)
  return breadthmeters_;
}
inline void PBAISStatic::set_breadthmeters(::google::protobuf::uint32 value) {
  
  breadthmeters_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.breadthMeters)
}

// optional uint32 lenghMeters = 8;
inline void PBAISStatic::clear_lenghmeters() {
  lenghmeters_ = 0u;
}
inline ::google::protobuf::uint32 PBAISStatic::lenghmeters() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.lenghMeters)
  return lenghmeters_;
}
inline void PBAISStatic::set_lenghmeters(::google::protobuf::uint32 value) {
  
  lenghmeters_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.lenghMeters)
}

// optional .PB_Enum_AIS_Fixing_Device fixingDevice = 9;
inline void PBAISStatic::clear_fixingdevice() {
  fixingdevice_ = 0;
}
inline ::PB_Enum_AIS_Fixing_Device PBAISStatic::fixingdevice() const {
  // @@protoc_insertion_point(field_get:PBAISStatic.fixingDevice)
  return static_cast< ::PB_Enum_AIS_Fixing_Device >(fixingdevice_);
}
inline void PBAISStatic::set_fixingdevice(::PB_Enum_AIS_Fixing_Device value) {
  
  fixingdevice_ = value;
  // @@protoc_insertion_point(field_set:PBAISStatic.fixingDevice)
}

inline const PBAISStatic* PBAISStatic::internal_default_instance() {
  return &PBAISStatic_default_instance_.get();
}
// -------------------------------------------------------------------

// PBAISVoyage

// optional int32 MMSI = 1;
inline void PBAISVoyage::clear_mmsi() {
  mmsi_ = 0;
}
inline ::google::protobuf::int32 PBAISVoyage::mmsi() const {
  // @@protoc_insertion_point(field_get:PBAISVoyage.MMSI)
  return mmsi_;
}
inline void PBAISVoyage::set_mmsi(::google::protobuf::int32 value) {
  
  mmsi_ = value;
  // @@protoc_insertion_point(field_set:PBAISVoyage.MMSI)
}

// optional uint32 utcTimeStamp = 2;
inline void PBAISVoyage::clear_utctimestamp() {
  utctimestamp_ = 0u;
}
inline ::google::protobuf::uint32 PBAISVoyage::utctimestamp() const {
  // @@protoc_insertion_point(field_get:PBAISVoyage.utcTimeStamp)
  return utctimestamp_;
}
inline void PBAISVoyage::set_utctimestamp(::google::protobuf::uint32 value) {
  
  utctimestamp_ = value;
  // @@protoc_insertion_point(field_set:PBAISVoyage.utcTimeStamp)
}

// optional string destination = 3;
inline void PBAISVoyage::clear_destination() {
  destination_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBAISVoyage::destination() const {
  // @@protoc_insertion_point(field_get:PBAISVoyage.destination)
  return destination_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISVoyage::set_destination(const ::std::string& value) {
  
  destination_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PBAISVoyage.destination)
}
inline void PBAISVoyage::set_destination(const char* value) {
  
  destination_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PBAISVoyage.destination)
}
inline void PBAISVoyage::set_destination(const char* value, size_t size) {
  
  destination_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PBAISVoyage.destination)
}
inline ::std::string* PBAISVoyage::mutable_destination() {
  
  // @@protoc_insertion_point(field_mutable:PBAISVoyage.destination)
  return destination_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBAISVoyage::release_destination() {
  // @@protoc_insertion_point(field_release:PBAISVoyage.destination)
  
  return destination_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISVoyage::set_allocated_destination(::std::string* destination) {
  if (destination != NULL) {
    
  } else {
    
  }
  destination_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destination);
  // @@protoc_insertion_point(field_set_allocated:PBAISVoyage.destination)
}

// optional string ETA = 4;
inline void PBAISVoyage::clear_eta() {
  eta_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PBAISVoyage::eta() const {
  // @@protoc_insertion_point(field_get:PBAISVoyage.ETA)
  return eta_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISVoyage::set_eta(const ::std::string& value) {
  
  eta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PBAISVoyage.ETA)
}
inline void PBAISVoyage::set_eta(const char* value) {
  
  eta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PBAISVoyage.ETA)
}
inline void PBAISVoyage::set_eta(const char* value, size_t size) {
  
  eta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PBAISVoyage.ETA)
}
inline ::std::string* PBAISVoyage::mutable_eta() {
  
  // @@protoc_insertion_point(field_mutable:PBAISVoyage.ETA)
  return eta_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PBAISVoyage::release_eta() {
  // @@protoc_insertion_point(field_release:PBAISVoyage.ETA)
  
  return eta_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PBAISVoyage::set_allocated_eta(::std::string* eta) {
  if (eta != NULL) {
    
  } else {
    
  }
  eta_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), eta);
  // @@protoc_insertion_point(field_set_allocated:PBAISVoyage.ETA)
}

// optional uint32 draftMetersX10 = 5;
inline void PBAISVoyage::clear_draftmetersx10() {
  draftmetersx10_ = 0u;
}
inline ::google::protobuf::uint32 PBAISVoyage::draftmetersx10() const {
  // @@protoc_insertion_point(field_get:PBAISVoyage.draftMetersX10)
  return draftmetersx10_;
}
inline void PBAISVoyage::set_draftmetersx10(::google::protobuf::uint32 value) {
  
  draftmetersx10_ = value;
  // @@protoc_insertion_point(field_set:PBAISVoyage.draftMetersX10)
}

inline const PBAISVoyage* PBAISVoyage::internal_default_instance() {
  return &PBAISVoyage_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PB_Enum_AIS_Device_Class_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PB_Enum_AIS_Device_Class_Type>() {
  return ::PB_Enum_AIS_Device_Class_Type_descriptor();
}
template <> struct is_proto_enum< ::PB_Enum_AIS_Commum_State> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PB_Enum_AIS_Commum_State>() {
  return ::PB_Enum_AIS_Commum_State_descriptor();
}
template <> struct is_proto_enum< ::PB_Enum_AIS_Pos_Accuracy> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PB_Enum_AIS_Pos_Accuracy>() {
  return ::PB_Enum_AIS_Pos_Accuracy_descriptor();
}
template <> struct is_proto_enum< ::PB_Enum_AIS_Fixing_Device> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PB_Enum_AIS_Fixing_Device>() {
  return ::PB_Enum_AIS_Fixing_Device_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AISData_2eproto__INCLUDED
